### PR TITLE
Homework 2 submitted

### PR DESCRIPTION
**Pull request by helium11**

### CODE REVIEW

**Comment by larissam** [comment]
Hey @helium11 , did you submit the right files? Let me know!

**Comment by helium11** [comment]
I... Think so?

**Comment by larissam** [comment]
The correct files should be in `Homework-2-revised` - these ones don't look like they have the answers. Let me know if you have trouble uploading the files! We can go through it in office hours if you'd like.

**Comment by larissam** [comment]
Check out the `Homework-2-revised` folder - should be in `~/JSD/JS-SF-11-resources/05-slackbot-lab/starter-code/Homework-2-revised`

**Comment by helium11** [comment]
Just put that file in homework folder and tried to git diff -- getting
content from the file in red. Not sure what I did wrong, can we go over
tomorrow in office hours?




On Wed, Jun 20, 2018 at 10:14 AM, Larissa Muramoto <notifications@github.com

**Pull request merged**
